# Generated by Django 5.2.7 on 2025-11-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_panel', '0008_trim_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='booking_notes',
            field=models.TextField(blank=True, help_text='Notes to display to customers during booking.'),
        ),
    ]
