# Generated by Django 5.2.7 on 2025-10-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_therapisttimeoffseries'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS time_off_therapist_start_idx RENAME TO scheduling__therapi_a3ea73_idx;",
            reverse_sql="ALTER INDEX IF EXISTS scheduling__therapi_a3ea73_idx RENAME TO time_off_therapist_start_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS time_off_therapist_end_idx RENAME TO scheduling__therapi_a4a62e_idx;",
            reverse_sql="ALTER INDEX IF EXISTS scheduling__therapi_a4a62e_idx RENAME TO time_off_therapist_end_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS time_off_occurrence_idx RENAME TO scheduling__series__e26958_idx;",
            reverse_sql="ALTER INDEX IF EXISTS scheduling__series__e26958_idx RENAME TO time_off_occurrence_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS time_off_skipped_idx RENAME TO scheduling__therapi_d91e29_idx;",
            reverse_sql="ALTER INDEX IF EXISTS scheduling__therapi_d91e29_idx RENAME TO time_off_skipped_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS time_off_series_start_idx RENAME TO scheduling__therapi_db0c7a_idx;",
            reverse_sql="ALTER INDEX IF EXISTS scheduling__therapi_db0c7a_idx RENAME TO time_off_series_start_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS time_off_series_active_idx RENAME TO scheduling__therapi_61e81e_idx;",
            reverse_sql="ALTER INDEX IF EXISTS scheduling__therapi_61e81e_idx RENAME TO time_off_series_active_idx;",
        ),
    ]
