# Generated by Django 5.2.7 on 2025-11-11 04:52

from django.db import migrations


INDEX_RENAMES = (
    ("time_off_therapist_start_idx", "scheduling__therapi_a3ea73_idx"),
    ("time_off_therapist_end_idx", "scheduling__therapi_a4a62e_idx"),
    ("time_off_occurrence_idx", "scheduling__series__e26958_idx"),
    ("time_off_skipped_idx", "scheduling__therapi_d91e29_idx"),
    ("time_off_series_start_idx", "scheduling__therapi_db0c7a_idx"),
    ("time_off_series_active_idx", "scheduling__therapi_61e81e_idx"),
    ("wh_hours_starts_idx", "scheduling__therapi_7c316a_idx"),
    ("wh_hours_ends_idx", "scheduling__therapi_1bedaa_idx"),
    ("wh_hours_series_idx", "scheduling__series__2b9f77_idx"),
    ("wh_hours_generated_idx", "scheduling__therapi_f6cade_idx"),
    ("scheduling_workinghours_therapist_is_skipped_idx", "scheduling__therapi_c6950a_idx"),
    ("wh_series_weekday_idx", "scheduling__therapi_cea9cd_idx"),
    ("wh_series_active_idx", "scheduling__therapi_94cc92_idx"),
)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_therapistworkinghours_is_skipped'),
    ]

    operations = [
        migrations.RunSQL(
            sql=f'ALTER INDEX IF EXISTS "{old}" RENAME TO "{new}";',
            reverse_sql=f'ALTER INDEX IF EXISTS "{new}" RENAME TO "{old}";',
        )
        for old, new in INDEX_RENAMES
    ]
