services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - lemon_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  lemon_postgres_data:
