version: "3.9"

services:
  app:
    build:
      context: .
    command: gunicorn lemon_spa.wsgi:application --bind 0.0.0.0:8000 --workers ${GUNICORN_WORKERS:-3}
    env_file:
      - .env
    environment:
      DJANGO_COLLECTSTATIC: ${DJANGO_COLLECTSTATIC:-1}
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      app:
        condition: service_started
    ports:
      - "80:80"
    volumes:
      - staticfiles:/staticfiles:ro
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lemon_spa}
      POSTGRES_USER: ${POSTGRES_USER:-lemon_spa}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lemon_spa}
    volumes:
      - lemon_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  lemon_postgres_data:
  staticfiles:
