# Generated by Django 5.2.7 on 2025-11-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='phoneverification',
            new_name='phone_verif_phone_n_4a579c_idx',
            old_name='phone_veri_phone_nu_e92ab4_idx',
        ),
        migrations.RenameIndex(
            model_name='phoneverification',
            new_name='phone_verif_is_veri_cf1110_idx',
            old_name='phone_veri_is_veri_326a8c_idx',
        ),
        migrations.RenameIndex(
            model_name='phoneverificationauditlog',
            new_name='phone_verif_phone_n_a4c6d2_idx',
            old_name='phone_veri_phone_nu_a20608_idx',
        ),
        migrations.RenameIndex(
            model_name='phoneverificationauditlog',
            new_name='phone_verif_created_f987e4_idx',
            old_name='phone_veri_created__fa9414_idx',
        ),
    ]
