# Generated by Django 5.2.7 on 2025-11-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentquestionnairelog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointmentquestionnairelog',
            new_name='appointment_appoint_21c9bd_idx',
            old_name='appointments_appt_questionnaire_status_idx',
        ),
    ]
